In [1]:
import torch

In [4]:
x = torch.randn((12, 21, 2, 3))
m = torch.mean(x, dim = (2,3))
m

tensor([[ 0.0984, -0.2021, -0.4047,  0.4716, -0.0642,  0.3127,  0.5775, -0.2682,
          0.1654, -0.1702, -0.0469, -0.0481,  0.1709, -0.1352,  0.0464, -0.1660,
         -0.5140, -0.1603, -0.4400,  0.4906,  0.6182],
        [-0.9649,  0.2961, -0.6534, -0.2670,  0.4399,  0.8832, -0.4768,  0.2813,
         -0.1479, -0.1623, -0.3323,  0.0403, -0.1284,  0.2692, -0.2926,  0.5434,
          0.7605, -0.7224,  0.0355, -0.1420,  0.3733],
        [ 0.5128,  0.0986, -0.9487, -0.1346, -0.4849, -0.0696, -0.5348, -0.1379,
          0.5341,  0.0852, -0.1640,  0.3096,  0.3732,  0.4025, -0.2091, -0.0818,
          0.3172, -0.4314, -0.3256,  0.6536,  0.0181],
        [ 0.3109,  0.1463, -0.7455,  0.2604, -0.4440,  0.8836, -0.0049, -0.0671,
          0.3082, -0.0284, -1.0450,  0.5885, -0.2671, -0.1447,  0.3509, -0.3268,
          0.0626,  0.2261,  0.4273,  0.5154,  0.6109],
        [-1.0162,  0.0339, -0.3999,  0.6652, -0.2655,  0.4947, -0.1686,  0.5537,
          0.9136,  0.6399,  0.1225,  0.0021, -0.397

In [6]:
torch.ones_like(x)*m.view(12, 21, 1, 1)

tensor([[[[ 0.0984,  0.0984,  0.0984],
          [ 0.0984,  0.0984,  0.0984]],

         [[-0.2021, -0.2021, -0.2021],
          [-0.2021, -0.2021, -0.2021]],

         [[-0.4047, -0.4047, -0.4047],
          [-0.4047, -0.4047, -0.4047]],

         ...,

         [[-0.4400, -0.4400, -0.4400],
          [-0.4400, -0.4400, -0.4400]],

         [[ 0.4906,  0.4906,  0.4906],
          [ 0.4906,  0.4906,  0.4906]],

         [[ 0.6182,  0.6182,  0.6182],
          [ 0.6182,  0.6182,  0.6182]]],


        [[[-0.9649, -0.9649, -0.9649],
          [-0.9649, -0.9649, -0.9649]],

         [[ 0.2961,  0.2961,  0.2961],
          [ 0.2961,  0.2961,  0.2961]],

         [[-0.6534, -0.6534, -0.6534],
          [-0.6534, -0.6534, -0.6534]],

         ...,

         [[ 0.0355,  0.0355,  0.0355],
          [ 0.0355,  0.0355,  0.0355]],

         [[-0.1420, -0.1420, -0.1420],
          [-0.1420, -0.1420, -0.1420]],

         [[ 0.3733,  0.3733,  0.3733],
          [ 0.3733,  0.3733,  0.3733]]],


      

In [4]:
pre_c = torch.special.expit(torch.randn((1, 1, 21, 20)))
c = (pre_c > .5).float()
torch.sum(c)/(21*20)


tensor(0.4905)

In [5]:
den = 0.2
c_hat = (den * pre_c) / ( (torch.norm(pre_c, p = 1)/(21*20)) + 1e-9)

torch.sum(c_hat)/(21*20)

tensor(0.2000)

In [6]:
c_hat

tensor([[[[0.2802, 0.2219, 0.2663, 0.1201, 0.1714, 0.2570, 0.0348, 0.1667,
           0.2304, 0.0871, 0.2050, 0.1797, 0.1093, 0.1286, 0.2354, 0.2121,
           0.1518, 0.1782, 0.2326, 0.1980],
          [0.2964, 0.2599, 0.2733, 0.2877, 0.1933, 0.0790, 0.1685, 0.1154,
           0.2352, 0.1974, 0.2517, 0.2818, 0.2969, 0.2889, 0.1073, 0.1848,
           0.2206, 0.2229, 0.0640, 0.2805],
          [0.1034, 0.1979, 0.1080, 0.1345, 0.3064, 0.2555, 0.3218, 0.1942,
           0.3122, 0.1269, 0.1003, 0.0746, 0.1708, 0.2159, 0.2260, 0.3005,
           0.0747, 0.3051, 0.3064, 0.2668],
          [0.2015, 0.1541, 0.3219, 0.1388, 0.1295, 0.1210, 0.3171, 0.1026,
           0.2090, 0.3005, 0.1500, 0.1371, 0.1706, 0.1929, 0.1504, 0.1578,
           0.1543, 0.1676, 0.1511, 0.3130],
          [0.1924, 0.1068, 0.0667, 0.2485, 0.0895, 0.0790, 0.0961, 0.3047,
           0.1963, 0.1741, 0.2590, 0.3414, 0.0579, 0.0858, 0.2631, 0.1724,
           0.2942, 0.0424, 0.1667, 0.0631],
          [0.0970, 0.2803, 0.3

In [93]:
c = (c_hat > ).float()
torch.sum(c)/(21*20)

tensor(0.8548)

In [33]:
x = torch.randn((12, 23, 4, 4))
x = torch.special.expit(x) 

d = 12*23

In [34]:
torch.mean(torch.abs((torch.norm(x, p = 1, dim = (2, 3)) / d) - 0.6))

tensor(0.5708)

In [ ]:
torch.floor(x+0.5)

In [35]:
x = torch.randn((12, 23, 4, 4))
y = torch.randn((12, 23, 4, 4))
d = 12*23

torch.mean(torch.norm(x-y, p = 2, dim = (2,3))**2 / d)

tensor(0.1150)